DROP TABLE SF_INFO;
DROP TABLE SF_VER_INFO;
DROP TABLE SF_COR_INFO;
DROP TABLE SF_ANALYSIS;

DROP TABLE FUNC_INFO;
DROP TABLE FUNC_VER_INFO;
DROP TABLE FUNC_COR_INFO;
DROP TABLE FUNC_ANALYSIS;

DROP TABLE BUG_INFO;
DROP TABLE BUG_COR_INFO;
DROP TABLE BUG_ANALYSIS;
DROP TABLE BUG_FIX_INFO;
DROP TABLE SIMI_BUG_INFO;
DROP TABLE INT_ANALYSIS;

DROP TABLE COMM_INFO;
DROP TABLE COMM_FILE_INFO;
DROP TABLE VER_INFO;

DROP TABLE EXP_INFO;
