mkdir _archives
mkdir _archives/Apache
wget -O _archives/Apache/CAMEL.tar "https://sourceforge.net/projects/irblsensitivity/files/Apache/CAMEL.tar"
wget -O _archives/Apache/HBASE.tar "https://sourceforge.net/projects/irblsensitivity/files/Apache/HBASE.tar"
wget -O _archives/Apache/HIVE.tar "https://sourceforge.net/projects/irblsensitivity/files/Apache/HIVE.tar"
mkdir _archives/Commons
wget -O _archives/Commons/CODEC.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/CODEC.tar"
wget -O _archives/Commons/COLLECTIONS.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/COLLECTIONS.tar"
wget -O _archives/Commons/COMPRESS.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/COMPRESS.tar"
wget -O _archives/Commons/CONFIGURATION.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/CONFIGURATION.tar"
wget -O _archives/Commons/CRYPTO.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/CRYPTO.tar"
wget -O _archives/Commons/CSV.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/CSV.tar"
wget -O _archives/Commons/IO.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/IO.tar"
wget -O _archives/Commons/LANG.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/LANG.tar"
wget -O _archives/Commons/MATH.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/MATH.tar"
wget -O _archives/Commons/WEAVER.tar "https://sourceforge.net/projects/irblsensitivity/files/Commons/WEAVER.tar"
mkdir _archives/JBoss
wget -O _archives/JBoss/ENTESB.tar "https://sourceforge.net/projects/irblsensitivity/files/JBoss/ENTESB.tar"
wget -O _archives/JBoss/JBMETA.tar "https://sourceforge.net/projects/irblsensitivity/files/JBoss/JBMETA.tar"
mkdir _archives/Wildfly
wget -O _archives/Wildfly/ELY.tar "https://sourceforge.net/projects/irblsensitivity/files/Wildfly/ELY.tar"
wget -O _archives/Wildfly/SWARM.tar "https://sourceforge.net/projects/irblsensitivity/files/Wildfly/SWARM.tar"
wget -O _archives/Wildfly/WFARQ.tar "https://sourceforge.net/projects/irblsensitivity/files/Wildfly/WFARQ.tar"
wget -O _archives/Wildfly/WFCORE.tar "https://sourceforge.net/projects/irblsensitivity/files/Wildfly/WFCORE.tar"
wget -O _archives/Wildfly/WFLY.tar "https://sourceforge.net/projects/irblsensitivity/files/Wildfly/WFLY.tar"
wget -O _archives/Wildfly/WFMP.tar "https://sourceforge.net/projects/irblsensitivity/files/Wildfly/WFMP.tar"
mkdir _archives/Spring
wget -O _archives/Spring/AMQP.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/AMQP.tar"
wget -O _archives/Spring/ANDROID.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/ANDROID.tar"
wget -O _archives/Spring/BATCH.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/BATCH.tar"
wget -O _archives/Spring/BATCHADM.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/BATCHADM.tar"
wget -O _archives/Spring/DATACMNS.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/DATACMNS.tar"
wget -O _archives/Spring/DATAGRAPH.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/DATAGRAPH.tar"
wget -O _archives/Spring/DATAJPA.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/DATAJPA.tar"
wget -O _archives/Spring/DATAMONGO.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/DATAMONGO.tar"
wget -O _archives/Spring/DATAREDIS.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/DATAREDIS.tar"
wget -O _archives/Spring/DATAREST.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/DATAREST.tar"
wget -O _archives/Spring/LDAP.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/LDAP.tar"
wget -O _archives/Spring/MOBILE.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/MOBILE.tar"
wget -O _archives/Spring/ROO.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/ROO.tar"
wget -O _archives/Spring/SEC.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SEC.tar"
wget -O _archives/Spring/SECOAUTH.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SECOAUTH.tar"
wget -O _archives/Spring/SGF.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SGF.tar"
wget -O _archives/Spring/SHDP.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SHDP.tar"
wget -O _archives/Spring/SHL.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SHL.tar"
wget -O _archives/Spring/SOCIAL.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SOCIAL.tar"
wget -O _archives/Spring/SOCIALFB.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SOCIALFB.tar"
wget -O _archives/Spring/SOCIALLI.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SOCIALLI.tar"
wget -O _archives/Spring/SOCIALTW.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SOCIALTW.tar"
wget -O _archives/Spring/SPR.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SPR.tar"
wget -O _archives/Spring/SWF.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SWF.tar"
wget -O _archives/Spring/SWS.tar "https://sourceforge.net/projects/irblsensitivity/files/Spring/SWS.tar"
mkdir _archives/Previous
wget -O _archives/Previous/AspectJ.tar "https://sourceforge.net/projects/irblsensitivity/files/Previous/AspectJ.tar"
wget -O _archives/Previous/JDT.tar "https://sourceforge.net/projects/irblsensitivity/files/Previous/JDT.tar"
wget -O _archives/Previous/PDE.tar "https://sourceforge.net/projects/irblsensitivity/files/Previous/PDE.tar"
wget -O _archives/Previous/SWT.tar "https://sourceforge.net/projects/irblsensitivity/files/Previous/SWT.tar"
wget -O _archives/Previous/ZXing.tar "https://sourceforge.net/projects/irblsensitivity/files/Previous/ZXing.tar"
